name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: codestyle
        run: git ls-files *.{cpp,hpp} | xargs clang-format -i --verbose && git diff --exit-code

      - name: build
        run: make

      - name: test
        run: make test